version: 1
policy:
  pullRequests: public
tasks:
  $let:
    user: ${event.sender.login}

    head_branch:
      $if: 'tasks_for == "github-pull-request"'
      then: ${event.pull_request.head.ref}
      else:
        $if: 'tasks_for == "github-push"'
        then: ${event.ref}
        else: ${event.release.target_commitish}

    head_rev:
      $if: 'tasks_for == "github-pull-request"'
      then: ${event.pull_request.head.sha}
      else:
        $if: 'tasks_for == "github-push"'
        then: ${event.after}
        else: ${event.release.tag_name}

    repository:
      $if: 'tasks_for == "github-pull-request"'
      then: ${event.pull_request.head.repo.html_url}
      else: ${event.repository.html_url}
  in:
      - taskId: {$eval: as_slugid("tests_task")}
        created: {$fromNow: ''}
        deadline: {$fromNow: '1 hour'}
        provisionerId: proj-relman
        workerType: ci
        payload:
          maxRunTime: 3600
          image: python:3.7
          command:
            - "/bin/bash"
            - "-lcx"
            - "git clone --quiet ${repository} &&
               cd coverage-crawler &&
               git -c advice.detachedHead=false checkout ${head_rev} &&
               pip install --quiet -r requirements.txt &&
               pip install --quiet -r test-requirements.txt &&
               flake8 . &&
               python -m pytest tests &&
               python setup.py sdist bdist_wheel &&
               pip install dist/coverage_crawler-1.0.0.tar.gz"
        metadata:
          name: coverage-crawler tests
          description: coverage-crawler tests
          owner: mcastelluccio@mozilla.com
          source: ${repository}/raw/${head_rev}/.taskcluster.yml
